### ISSUE TITLE
Missing MonadFail instance for BinaryParser

### ISSUE THREAD

**Issue by k0001** [nikita-volkov/binary-parser#5]
`fail` would do what `BinaryParser.failure` already does.

The motivation is the same as in https://github.com/nikita-volkov/hasql/pull/129 — That is, simplify writing failing parsers. Over in `hasql`, this change would make it easier to implement `MonadFail` for `Composite`, but generally speaking, being able to use `fail` and failing patterns in `BinaryParser` will be useful too.

I tried to implement this, but I found some strange situation regarding how `BasePrelude` exports `MonadFail` without its `fail` method, and then I noticed that in `BinaryParser.Prelude` you also hide `fail`, so I thought maybe you'll know best how to rearrange things. Presumably `BasePrelude` should be exporting all of `MonadFail(..)`.

**Comment by nikita-volkov** [comment]
Done

**Comment by nikita-volkov** [comment]
BTW, the BasePrelude confusion has also been resolved. It was due to support for old GHC versions, which has now been removed. BasePrelude now exports `fail` from `MonadFail`.

**Comment by k0001** [comment]
Excellent, @nikita-volkov! Thank you =)
